### ISSUE TITLE
AttributeError: 'FietsersbondDock' object has no attribute 'toolbar'

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [fietsersbond-vzw/fb_tools_mow#1]
Sometimes , after first installation this message occurs:

Couldn't load plugin 'FB_tools' due to an error when calling its initGui() method 

AttributeError: 'FietsersbondDock' object has no attribute 'toolbar' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python\qgis\utils.py", line 344, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/Jo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\FB_tools\FB_tools.py", line 657, in initGui
    parent=self.iface.mainWindow())
  File "C:/Users/Jo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\FB_tools\FB_tools.py", line 638, in add_action
    self.toolbar.addAction(action)
AttributeError: 'FietsersbondDock' object has no attribute 'toolbar'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.6.0-Noosa Noosa, 58734527ab 

Python Path:
C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python
C:/Users/Jo/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Jo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.6\bin\python37.zip
C:\PROGRA~1\QGIS3~1.6\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib
C:\Program Files\QGIS 3.6\bin
C:\PROGRA~1\QGIS3~1.6\apps\Python37
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Jo/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Jo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2mapillary
C:\Users\Jo\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2mapillary\extlibs
D:/Google Drive/P_MOW-light

**Comment by PolyglotOpenstreetmap** [comment]
This seems to be related to DB_USERNAME and DB_PASSWORD being set to empty strings.

**Comment by PolyglotOpenstreetmap** [comment]
This commit should resolve this: cb9f4e596fec379c48d25f437423dbe049ce3ae6

**Comment by PolyglotOpenstreetmap** [comment]
not that one, this one: 27bb6562c5501d9b62ba2219696b86682df6ae81
